name: Publish Docker

on:
  push:
    branches: [ main, ios ]

jobs:
  android:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/ios'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push docker
        uses: docker/build-push-action@v3
        with:
          context: ./android
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/android-pwa-builder:latest

  ios:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/android'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'true'
          fetch-depth: 5

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build
        working-directory: ./ios/PWABuilder.IOS.Cli
        run: |
          dotnet publish -c Release -o ./bin/publish
          rm ./bin/publish/*.pdb -f
          rm ./bin/publish/*.dbg -f

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push docker
        uses: docker/build-push-action@v3
        with:
          context: ./ios/PWABuilder.IOS.Cli
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ios-pwa-builder:latest
